/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_app;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    Connection conn;
    Color enter = new Color(51, 102, 255);
    Color exit = new Color(51, 51, 51);

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        loadDG();
        loadS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        quanlytacgiaBtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        quanlytheloaiBtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        taophieu = new javax.swing.JPanel();
        danhsachphat = new javax.swing.JLabel();
        danhsachphatBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        trasach = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        muonsach = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        quanlydocgiaBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        quanlynhaxuatbanBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        quanlysachBtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        thongke = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        sl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        dg = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        sach = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sachTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        docgiaTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tonkho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        setMinimumSize(new java.awt.Dimension(1200, 670));
        setPreferredSize(new java.awt.Dimension(1200, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 670));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 670));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_menu_48px_1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hệ thống quản lý thư viện");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/male_user_50px.png"))); // NOI18N

        user.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        user.setText("Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(menu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setMinimumSize(new java.awt.Dimension(240, 620));
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 620));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 51, 51));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/home_24px.png"))); // NOI18N
        jLabel4.setText("Trang chủ");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 40));

        quanlytacgiaBtn.setBackground(new java.awt.Color(51, 51, 51));
        quanlytacgiaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlytacgiaBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quanlytacgiaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quanlytacgiaBtnMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        jLabel7.setText("Quản lý tác giả");

        javax.swing.GroupLayout quanlytacgiaBtnLayout = new javax.swing.GroupLayout(quanlytacgiaBtn);
        quanlytacgiaBtn.setLayout(quanlytacgiaBtnLayout);
        quanlytacgiaBtnLayout.setHorizontalGroup(
            quanlytacgiaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanlytacgiaBtnLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        quanlytacgiaBtnLayout.setVerticalGroup(
            quanlytacgiaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quanlytacgiaBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(quanlytacgiaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 30));

        quanlytheloaiBtn.setBackground(new java.awt.Color(51, 51, 51));
        quanlytheloaiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlytheloaiBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quanlytheloaiBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quanlytheloaiBtnMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        jLabel8.setText("Quản lý thể loại");

        javax.swing.GroupLayout quanlytheloaiBtnLayout = new javax.swing.GroupLayout(quanlytheloaiBtn);
        quanlytheloaiBtn.setLayout(quanlytheloaiBtnLayout);
        quanlytheloaiBtnLayout.setHorizontalGroup(
            quanlytheloaiBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanlytheloaiBtnLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        quanlytheloaiBtnLayout.setVerticalGroup(
            quanlytheloaiBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanlytheloaiBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(quanlytheloaiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 40));

        taophieu.setBackground(new java.awt.Color(51, 51, 51));
        taophieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taophieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                taophieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                taophieuMouseExited(evt);
            }
        });

        danhsachphat.setBackground(new java.awt.Color(255, 255, 255));
        danhsachphat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        danhsachphat.setForeground(new java.awt.Color(255, 255, 255));
        danhsachphat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Book_26px.png"))); // NOI18N
        danhsachphat.setText("Tạo/gia hạn phiếu");

        javax.swing.GroupLayout taophieuLayout = new javax.swing.GroupLayout(taophieu);
        taophieu.setLayout(taophieuLayout);
        taophieuLayout.setHorizontalGroup(
            taophieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taophieuLayout.createSequentialGroup()
                .addComponent(danhsachphat, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
        taophieuLayout.setVerticalGroup(
            taophieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taophieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(danhsachphat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(taophieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 40));

        danhsachphatBtn.setBackground(new java.awt.Color(51, 51, 51));
        danhsachphatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhsachphatBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                danhsachphatBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                danhsachphatBtnMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        jLabel11.setText("Danh sách phạt");

        javax.swing.GroupLayout danhsachphatBtnLayout = new javax.swing.GroupLayout(danhsachphatBtn);
        danhsachphatBtn.setLayout(danhsachphatBtnLayout);
        danhsachphatBtnLayout.setHorizontalGroup(
            danhsachphatBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(danhsachphatBtnLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        danhsachphatBtnLayout.setVerticalGroup(
            danhsachphatBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(danhsachphatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 40));

        logoutBtn.setBackground(new java.awt.Color(102, 102, 255));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Exit_26px.png"))); // NOI18N
        jLabel24.setText("Đăng xuất");

        javax.swing.GroupLayout logoutBtnLayout = new javax.swing.GroupLayout(logoutBtn);
        logoutBtn.setLayout(logoutBtnLayout);
        logoutBtnLayout.setHorizontalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );
        logoutBtnLayout.setVerticalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutBtnLayout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel4.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 240, 40));

        trasach.setBackground(new java.awt.Color(51, 51, 51));
        trasach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trasachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trasachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trasachMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        jLabel10.setText("Trả sách");

        javax.swing.GroupLayout trasachLayout = new javax.swing.GroupLayout(trasach);
        trasach.setLayout(trasachLayout);
        trasachLayout.setHorizontalGroup(
            trasachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trasachLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        trasachLayout.setVerticalGroup(
            trasachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trasachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(trasach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 240, 40));

        muonsach.setBackground(new java.awt.Color(51, 51, 51));
        muonsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muonsachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                muonsachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                muonsachMouseExited(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        jLabel25.setText("Mượn sách");

        javax.swing.GroupLayout muonsachLayout = new javax.swing.GroupLayout(muonsach);
        muonsach.setLayout(muonsachLayout);
        muonsachLayout.setHorizontalGroup(
            muonsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(muonsachLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        muonsachLayout.setVerticalGroup(
            muonsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, muonsachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(muonsach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 40));

        quanlydocgiaBtn.setBackground(new java.awt.Color(51, 51, 51));
        quanlydocgiaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlydocgiaBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quanlydocgiaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quanlydocgiaBtnMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        jLabel12.setText("Quản lý độc giả");

        javax.swing.GroupLayout quanlydocgiaBtnLayout = new javax.swing.GroupLayout(quanlydocgiaBtn);
        quanlydocgiaBtn.setLayout(quanlydocgiaBtnLayout);
        quanlydocgiaBtnLayout.setHorizontalGroup(
            quanlydocgiaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        quanlydocgiaBtnLayout.setVerticalGroup(
            quanlydocgiaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanlydocgiaBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(quanlydocgiaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 40));

        quanlynhaxuatbanBtn.setBackground(new java.awt.Color(51, 51, 51));
        quanlynhaxuatbanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlynhaxuatbanBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quanlynhaxuatbanBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quanlynhaxuatbanBtnMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        jLabel9.setText("Quản lý NXB");

        javax.swing.GroupLayout quanlynhaxuatbanBtnLayout = new javax.swing.GroupLayout(quanlynhaxuatbanBtn);
        quanlynhaxuatbanBtn.setLayout(quanlynhaxuatbanBtnLayout);
        quanlynhaxuatbanBtnLayout.setHorizontalGroup(
            quanlynhaxuatbanBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanlynhaxuatbanBtnLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        quanlynhaxuatbanBtnLayout.setVerticalGroup(
            quanlynhaxuatbanBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quanlynhaxuatbanBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(quanlynhaxuatbanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 40));

        quanlysachBtn.setBackground(new java.awt.Color(51, 51, 51));
        quanlysachBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlysachBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quanlysachBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quanlysachBtnMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel6.setText("Quản lý sách");

        javax.swing.GroupLayout quanlysachBtnLayout = new javax.swing.GroupLayout(quanlysachBtn);
        quanlysachBtn.setLayout(quanlysachBtnLayout);
        quanlysachBtnLayout.setHorizontalGroup(
            quanlysachBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanlysachBtnLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        quanlysachBtnLayout.setVerticalGroup(
            quanlysachBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(quanlysachBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 40));

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel3.setText("Thoát");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 240, 40));

        thongke.setBackground(new java.awt.Color(51, 51, 51));
        thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thongkeMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        jLabel5.setText("Thống kê");

        javax.swing.GroupLayout thongkeLayout = new javax.swing.GroupLayout(thongke);
        thongke.setLayout(thongkeLayout);
        thongkeLayout.setHorizontalGroup(
            thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongkeLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        thongkeLayout.setVerticalGroup(
            thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 240, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 620));

        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        jPanel13.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 80));

        sl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        sl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                slAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel13.add(sl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, 50));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, 110));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Tồn kho");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 140, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Số lượng độc giả");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 200, 30));

        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(51, 102, 255)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_People_50px.png"))); // NOI18N

        dg.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dg.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dgAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dg, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 200, 110));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Số sách đã mượn");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 200, 30));

        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Sell_26px.png"))); // NOI18N

        sach.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        sach.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sachAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(sach, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sach, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 200, 110));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Thông tin độc giả");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 170, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Thông tin sách");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 170, 20));

        sachTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tiêu đề", "Tác giả", "Thể loại", "Năm xuất bản"
            }
        ));
        jScrollPane2.setViewportView(sachTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 880, 150));

        docgiaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(docgiaTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 880, 170));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Số lượng sách");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 200, 30));

        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(51, 102, 255)));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_People_50px.png"))); // NOI18N

        tonkho.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tonkho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tonkhoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tonkho, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tonkho, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 190, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadS() {
        sachTable.removeAll();
        try {
            conn = ConnectDB.KetnoiDB();
            String sql = "SELECT sach.MaSach,sach.TenSach,tacgia.TenTacGia,theloai.TenTheLoai,nxb.TenNXB From sach join tacgia on sach.MaTacGia=tacgia.MaTacGia join theloai on sach.MaTheLoai=theloai.MaTheLoai JOIN nxb on sach.MaNXB=nxb.MaNXB;";
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery(sql);

            String[] arr = {"Mã sách", "Tên sách", "Tên tác giả", "Thể loại", " NXB"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1).toString());
                v.add(rs.getString(2).toString());
                v.add(rs.getString(3).toString());
                v.add(rs.getString(4).toString());
                v.add(rs.getString(5).toString());

                model.addRow(v);
            }
            sachTable.setModel(model);
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadDG() {
        docgiaTable.removeAll();
        try {
            conn = ConnectDB.KetnoiDB();
            String sql = "Select MaDG,TenDG,NgaySinh,DiaChi,SDT From docgia";
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery(sql);
            String[] arr = {"Mã độc giả", "Tên độc giả", "ngày sinh", "Địa chỉ", "Số điện thoại"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1).toString());
                v.add(rs.getString(2).toString());
                v.add(rs.getString(3).toString());
                v.add(rs.getString(4).toString());
                v.add(rs.getString(5).toString());

                model.addRow(v);
            }
            docgiaTable.setModel(model);
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void quanlytacgiaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlytacgiaBtnMouseClicked
        // TODO add your handling code here:
        ManagementAuthor author = new ManagementAuthor();
        author.setVisible(true);
        dispose();
    }//GEN-LAST:event_quanlytacgiaBtnMouseClicked

    private void quanlytheloaiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlytheloaiBtnMouseClicked
        // TODO add your handling code here:
        ManagementCategory category = new ManagementCategory();
        category.setVisible(true);
        dispose();
    }//GEN-LAST:event_quanlytheloaiBtnMouseClicked

    private void taophieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taophieuMouseClicked
        // TODO add your handling code here:
        taovagiahanphieu t=new taovagiahanphieu();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_taophieuMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void quanlytacgiaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlytacgiaBtnMouseEntered
        // TODO add your handling code here:
        quanlytacgiaBtn.setBackground(enter);
    }//GEN-LAST:event_quanlytacgiaBtnMouseEntered

    private void quanlytacgiaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlytacgiaBtnMouseExited
        // TODO add your handling code here:
        quanlytacgiaBtn.setBackground(exit);
    }//GEN-LAST:event_quanlytacgiaBtnMouseExited

    private void quanlytheloaiBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlytheloaiBtnMouseEntered
        // TODO add your handling code here:
        quanlytheloaiBtn.setBackground(enter);
    }//GEN-LAST:event_quanlytheloaiBtnMouseEntered

    private void quanlytheloaiBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlytheloaiBtnMouseExited
        // TODO add your handling code here:
        quanlytheloaiBtn.setBackground(exit);
    }//GEN-LAST:event_quanlytheloaiBtnMouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseEntered

    private void taophieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taophieuMouseEntered
        // TODO add your handling code here:
        taophieu.setBackground(enter);
    }//GEN-LAST:event_taophieuMouseEntered

    private void taophieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taophieuMouseExited
        taophieu.setBackground(exit);        // TODO add your handling code here:
    }//GEN-LAST:event_taophieuMouseExited

    private void danhsachphatBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_danhsachphatBtnMouseEntered
        danhsachphatBtn.setBackground(enter);        // TODO add your handling code here:
    }//GEN-LAST:event_danhsachphatBtnMouseEntered

    private void danhsachphatBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_danhsachphatBtnMouseExited
        danhsachphatBtn.setBackground(exit);        // TODO add your handling code here:
    }//GEN-LAST:event_danhsachphatBtnMouseExited

    private void trasachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trasachMouseClicked
        // TODO add your handling code here:
    
    trasach t=new trasach();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_trasachMouseClicked

    private void trasachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trasachMouseEntered
        // TODO add your handling code here:
        trasach.setBackground(enter);
    }//GEN-LAST:event_trasachMouseEntered

    private void trasachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trasachMouseExited
        trasach.setBackground(exit);        // TODO add your handling code here:
    }//GEN-LAST:event_trasachMouseExited

    private void muonsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muonsachMouseClicked
        muonsach m=new muonsach();
        m.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_muonsachMouseClicked

    private void muonsachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muonsachMouseEntered
        muonsach.setBackground(enter);        // TODO add your handling code here:
    }//GEN-LAST:event_muonsachMouseEntered

    private void muonsachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muonsachMouseExited
        muonsach.setBackground(exit);        // TODO add your handling code here:
    }//GEN-LAST:event_muonsachMouseExited

    private void quanlydocgiaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlydocgiaBtnMouseClicked
        ManagementReader reader = new ManagementReader();
        reader.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_quanlydocgiaBtnMouseClicked

    private void quanlydocgiaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlydocgiaBtnMouseEntered
        quanlydocgiaBtn.setBackground(enter);
        // TODO add your handling code here:
    }//GEN-LAST:event_quanlydocgiaBtnMouseEntered

    private void quanlydocgiaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlydocgiaBtnMouseExited
        quanlydocgiaBtn.setBackground(exit);
        // TODO add your handling code here:
    }//GEN-LAST:event_quanlydocgiaBtnMouseExited

    private void quanlynhaxuatbanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlynhaxuatbanBtnMouseClicked
        ManagementPublisher publisher = new ManagementPublisher();
        publisher.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_quanlynhaxuatbanBtnMouseClicked

    private void quanlynhaxuatbanBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlynhaxuatbanBtnMouseEntered
        quanlynhaxuatbanBtn.setBackground(enter);
        // TODO add your handling code here:
    }//GEN-LAST:event_quanlynhaxuatbanBtnMouseEntered

    private void quanlynhaxuatbanBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlynhaxuatbanBtnMouseExited
        quanlynhaxuatbanBtn.setBackground(exit);
        // TODO add your handling code here:
    }//GEN-LAST:event_quanlynhaxuatbanBtnMouseExited

    private void quanlysachBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlysachBtnMouseClicked
        ManagementBook book = new ManagementBook();
        book.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_quanlysachBtnMouseClicked

    private void quanlysachBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlysachBtnMouseEntered
        quanlysachBtn.setBackground(enter);
        // TODO add your handling code here:
    }//GEN-LAST:event_quanlysachBtnMouseEntered

    private void quanlysachBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlysachBtnMouseExited
        quanlysachBtn.setBackground(exit);
        // TODO add your handling code here:
    }//GEN-LAST:event_quanlysachBtnMouseExited

    private void danhsachphatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_danhsachphatBtnMouseClicked
        OverdueNotice notice = new OverdueNotice();
        notice.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_danhsachphatBtnMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void loadsach() {
        try {

            conn = ConnectDB.KetnoiDB();
            String sql = "Select SUM(SoLuong) from sach";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int tongSoLuong = rs.getInt(1); // Lấy tổng số lượng từ kết quả truy vấn
                sl.setText(String.valueOf(tongSoLuong)); // Đưa giá trị vào text field
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    private void slAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_slAncestorAdded
        loadsach();
    }//GEN-LAST:event_slAncestorAdded

    private void loaddg() {
        try {
            conn = ConnectDB.KetnoiDB();
            String sql = "Select Count(tendg) from docgia";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int tongdg = rs.getInt(1);
                dg.setText(String.valueOf(tongdg));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void dgAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dgAncestorAdded
        loaddg();
        // TODO add your handling code here:
    }//GEN-LAST:event_dgAncestorAdded

    private void loadmuon() {
        try {
            conn = ConnectDB.KetnoiDB();
            String sql = "Select SUM(soluong) from chitietmuon";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int tongmuon = rs.getInt(1);
                sach.setText(String.valueOf(tongmuon));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    private void sachAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sachAncestorAdded
        loadmuon();
// TODO add your handling code here:
    }//GEN-LAST:event_sachAncestorAdded

    private void loadtk() {
        try {
            conn = ConnectDB.KetnoiDB();
            String sql = "SELECT (SELECT SUM(SoLuong) FROM sach) - (SELECT SUM(SoLuong) FROM chitietmuon) AS HieuSoLuong";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int hieuSoLuong = rs.getInt("HieuSoLuong");
                tonkho.setText(String.valueOf(hieuSoLuong));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void tonkhoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tonkhoAncestorAdded
        loadtk();
// TODO add your handling code here:
    }//GEN-LAST:event_tonkhoAncestorAdded

    private void thongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeMouseEntered
        // TODO add your handling code here:
        thongke.setBackground(enter);
    }//GEN-LAST:event_thongkeMouseEntered

    private void thongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeMouseExited
        // TODO add your handling code here:
        thongke.setBackground(exit);
    }//GEN-LAST:event_thongkeMouseExited

    private void thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeMouseClicked
        // TODO add your handling code here:
        thongke t=new thongke();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_thongkeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel danhsachphat;
    private javax.swing.JPanel danhsachphatBtn;
    private javax.swing.JLabel dg;
    private javax.swing.JTable docgiaTable;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JLabel menu;
    private javax.swing.JPanel muonsach;
    private javax.swing.JPanel quanlydocgiaBtn;
    private javax.swing.JPanel quanlynhaxuatbanBtn;
    private javax.swing.JPanel quanlysachBtn;
    private javax.swing.JPanel quanlytacgiaBtn;
    private javax.swing.JPanel quanlytheloaiBtn;
    private javax.swing.JLabel sach;
    private javax.swing.JTable sachTable;
    private javax.swing.JLabel sl;
    private javax.swing.JPanel taophieu;
    private javax.swing.JPanel thongke;
    private javax.swing.JLabel tonkho;
    private javax.swing.JPanel trasach;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
