/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_app;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import library_app.ConnectDB;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class ManagementBook extends javax.swing.JFrame {
Connection conn;

    /**
     * Creates new form ManagementBook
     */
    public ManagementBook() {
        initComponents();
        load();
        loadComboboxAu();
        loadComboboxCa();
        loadComboboxnxb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idEdt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nameBookEdt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dateEdt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        QuantityEdt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        priceEdt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        pageEdt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        luuBtn = new javax.swing.JButton();
        suaBtn = new javax.swing.JButton();
        reportBtn = new javax.swing.JButton();
        nxbEdt = new javax.swing.JComboBox<>();
        authorEdt = new javax.swing.JComboBox<>();
        categoryEdt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        xoaBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sachTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ManagementBook");
        setMinimumSize(new java.awt.Dimension(1200, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel1.setText("Quay lại");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã sách");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 20));

        idEdt.setBackground(new java.awt.Color(102, 102, 255));
        idEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        idEdt.setForeground(new java.awt.Color(255, 255, 255));
        idEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        idEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idEdt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idEdtFocusLost(evt);
            }
        });
        jPanel1.add(idEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 440, 40));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên sách");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        nameBookEdt.setBackground(new java.awt.Color(102, 102, 255));
        nameBookEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        nameBookEdt.setForeground(new java.awt.Color(255, 255, 255));
        nameBookEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        nameBookEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(nameBookEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 40));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nhà xuất bản");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tên Tác Giả");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, -1));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Thể loại");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        dateEdt.setBackground(new java.awt.Color(102, 102, 255));
        dateEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        dateEdt.setForeground(new java.awt.Color(255, 255, 255));
        dateEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        dateEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(dateEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 180, 40));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Năm xuất bản");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        QuantityEdt.setBackground(new java.awt.Color(102, 102, 255));
        QuantityEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        QuantityEdt.setForeground(new java.awt.Color(255, 255, 255));
        QuantityEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        QuantityEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        QuantityEdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QuantityEdtKeyReleased(evt);
            }
        });
        jPanel1.add(QuantityEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 180, 40));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Số lượng");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        priceEdt.setBackground(new java.awt.Color(102, 102, 255));
        priceEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        priceEdt.setForeground(new java.awt.Color(255, 255, 255));
        priceEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        priceEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        priceEdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceEdtKeyReleased(evt);
            }
        });
        jPanel1.add(priceEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 170, 40));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Giá tiền");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        pageEdt.setBackground(new java.awt.Color(102, 102, 255));
        pageEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        pageEdt.setForeground(new java.awt.Color(255, 255, 255));
        pageEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        pageEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pageEdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pageEdtKeyReleased(evt);
            }
        });
        jPanel1.add(pageEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 170, 40));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Số trang");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        luuBtn.setBackground(new java.awt.Color(255, 102, 102));
        luuBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luuBtn.setForeground(new java.awt.Color(255, 255, 255));
        luuBtn.setText("Lưu");
        luuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(luuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, 50));

        suaBtn.setBackground(new java.awt.Color(255, 102, 102));
        suaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        suaBtn.setForeground(new java.awt.Color(255, 255, 255));
        suaBtn.setText("Sửa");
        suaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(suaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 100, 50));

        reportBtn.setBackground(new java.awt.Color(255, 102, 102));
        reportBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reportBtn.setForeground(new java.awt.Color(255, 255, 255));
        reportBtn.setText("In báo cáo");
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });
        jPanel1.add(reportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, 50));

        nxbEdt.setBackground(new java.awt.Color(102, 102, 255));
        nxbEdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nxbEdt.setForeground(new java.awt.Color(255, 255, 255));
        nxbEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        nxbEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxbEdtActionPerformed(evt);
            }
        });
        jPanel1.add(nxbEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 170, 40));

        authorEdt.setBackground(new java.awt.Color(102, 102, 255));
        authorEdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        authorEdt.setForeground(new java.awt.Color(255, 255, 255));
        authorEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(authorEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, 40));

        categoryEdt.setBackground(new java.awt.Color(102, 102, 255));
        categoryEdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoryEdt.setForeground(new java.awt.Color(255, 255, 255));
        categoryEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(categoryEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 170, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 30, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 30, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        xoaBtn.setBackground(new java.awt.Color(255, 102, 102));
        xoaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        xoaBtn.setForeground(new java.awt.Color(255, 255, 255));
        xoaBtn.setText("Xóa");
        xoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(xoaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 100, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 670));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jLabel2.setText("Quản lý Sách");

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        sachTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sachTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sachTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 680, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   private void reportJasper(){
       try {
           conn=ConnectDB.KetnoiDB();
           String path="C:\\Users\\Admin\\JaspersoftWorkspace\\MyReports\\Book.jrxml";
           JasperReport jr= JasperCompileManager.compileReport(path);
           JasperPrint jp=JasperFillManager.fillReport(jr, null,conn);
           JasperViewer.viewReport(jp,false);
          conn.close();
       } catch (Exception e) {
       e.printStackTrace();
       }
   }
    private String nameAu() throws SQLException{
       String name=null;
       String nameAu=authorEdt.getSelectedItem().toString();  
           conn=ConnectDB.KetnoiDB();
           String sql="select MaTacGia From tacgia Where TenTacGia=?";
           PreparedStatement ps=conn.prepareStatement(sql);
           ps.setString(1, nameAu);
           ResultSet rs=ps.executeQuery();
           while(rs.next()){
            name=   rs.getString("MaTacGia");
           }
      return name;
   }
      private String nameCa() throws SQLException{
          String name=null;
       String nameCa=categoryEdt.getSelectedItem().toString();
      
           conn=ConnectDB.KetnoiDB();
           String sql="select MaTheLoai From theloai Where TenTheLoai=?";
           PreparedStatement ps=conn.prepareStatement(sql);
           ps.setString(1, nameCa);
           ResultSet rs=ps.executeQuery();
           while (rs.next()) {              
              name= rs.getString("MaTheLoai");
          }
       
      return name;
   }
         private String namenxb() throws SQLException{
             String name = null;
       String namenxb=nxbEdt.getSelectedItem().toString();
           conn=ConnectDB.KetnoiDB();
           String sql="select MaNXB From nxb Where TenNXB=?";
           PreparedStatement ps=conn.prepareStatement(sql);
           ps.setString(1, namenxb);
           ResultSet rs=ps.executeQuery();
             while (rs.next()) {                 
                 name=rs.getString("MaNXb");
             }
       
      return name;
   }
    private boolean checkDuplicate(){
         String id=idEdt.getText().toString();
        boolean isExit=false;
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Select * From sach Where MaSach='"+id+"'";
            Statement st=conn.createStatement();
            ResultSet s=st.executeQuery(sql);
            
            if (s.next()) {
                isExit=true;
            }else{
                isExit=false;
            }
                    
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isExit;
    }
    private void loadComboboxnxb(){
       try {
           conn=ConnectDB.KetnoiDB();
           String sql= "select TenNXB From nxb";
           PreparedStatement ps=conn.prepareStatement(sql);
           ResultSet rs=ps.executeQuery();
           while (rs.next()) {
               
               nxbEdt.addItem(rs.getString("TenNXB"));
           }
           
           
       } catch (Exception e) {
       e.printStackTrace();
       }
   }
    private void loadComboboxCa(){
        try {
           conn=ConnectDB.KetnoiDB();
           String sql= "select TenTheLoai From theloai";
           PreparedStatement ps=conn.prepareStatement(sql);
           ResultSet rs=ps.executeQuery();
           while (rs.next()) {
               categoryEdt.addItem(rs.getString("TenTheLoai"));
           }
  
       } catch (Exception e) {
       e.printStackTrace();
       }
    }
    private void loadComboboxAu(){
       try {
           conn=ConnectDB.KetnoiDB();
           String sql= "select TenTacGia From tacgia";
           PreparedStatement ps=conn.prepareStatement(sql);
           ResultSet rs=ps.executeQuery();
           while (rs.next()) {
               
               authorEdt.addItem(rs.getString("TenTacGia"));
           }
           
           
       } catch (Exception e) {
       e.printStackTrace();
       }
   }
    private void deleteBook(){
         String id=idEdt.getText().toString();

        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Delete from sach Where MaSach='"+id+"'";
            Statement s=conn.createStatement();
            s.executeUpdate(sql);
            load();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void insertBook(){
         String id=idEdt.getText().toString();
         String nameBook=nameBookEdt.getText().toString();
         String nameAu=authorEdt.getSelectedItem().toString();
         String nameCa=categoryEdt.getSelectedItem().toString();
         String namePub=nxbEdt.getSelectedItem().toString();
         String date=dateEdt.getText().toString();
         String price=priceEdt.getText().toString();
         String quantity=QuantityEdt.getText().toString();
         String page=pageEdt.getText().toString();

        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Insert sach Values (?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1, id);
            ps.setString(2, nameBook);
            ps.setString(3, nameAu());
            ps.setString(4, nameCa());
            ps.setString(5, namenxb());
            ps.setString(6, date);
            ps.setString(7, price);
            ps.setString(8, quantity);
            ps.setString(9, page);
            ps.executeUpdate();
            load();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void updateBook(){
         String id=idEdt.getText().toString();
         String nameBook=nameBookEdt.getText().toString();
         String nameAu=authorEdt.getSelectedItem().toString();
         String nameCa=categoryEdt.getSelectedItem().toString();
         String namePub=nxbEdt.getSelectedItem().toString();
         String date=dateEdt.getText().toString();
         String price=priceEdt.getText().toString();
         String quantity=QuantityEdt.getText().toString();
         String page=pageEdt.getText().toString();

        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Update sach set TenSach=?,MaTacGia=?,MaTheLoai=?,MaNXB=?,NamXuatBan=?,GiaTien=?,SoLuong=?,SoTrang=? Where MaSach=?";
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1, nameBook);
            ps.setString(2, nameAu());
            ps.setString(3, nameCa());
            ps.setString(4, namenxb());
            ps.setString(5, date);
            ps.setString(6, price);
            ps.setString(7, quantity);
            ps.setString(8, page);
            ps.setString(9,id);
            ps.executeUpdate();
            load();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void load(){
              sachTable.removeAll();
        try {
            conn=ConnectDB.KetnoiDB();
                String sql="SELECT sach.MaSach,sach.TenSach,tacgia.TenTacGia,theloai.TenTheLoai,nxb.TenNXB,YEAR(sach.NamXuatBan),sach.GiaTien,sach.SoLuong,sach.SoTrang from sach JOIN tacgia ON sach.MaTacGia=tacgia.MaTacGia JOIN theloai on sach.MaTheLoai=theloai.MaTheLoai JOIN nxb on sach.MaNXB=nxb.MaNXB;";
            Statement s=conn.createStatement();
            ResultSet rs=s.executeQuery(sql);
            
            String[] arr={"Mã sách","Tên sách","Tên tác giả","Tên thể loại","Tên NXB","Năm XB","Giá Tiền","Số lượng","Số trang"};
            DefaultTableModel model=new DefaultTableModel(arr,0);
            while (rs.next()) {
                Vector v=new Vector();
                v.add(rs.getString(1).toString());
                v.add(rs.getString(2).toString());
                v.add(rs.getString(3).toString());
                v.add(rs.getString(4).toString()); 
                v.add(rs.getString(5).toString()); 
                v.add(rs.getString(6).toString()); 
                v.add(rs.getString(7).toString()); 
                v.add(rs.getString(8).toString()); 
                v.add(rs.getString(9).toString()); 
                model.addRow(v);
            }
            sachTable.setModel(model);
            conn.close();
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void luuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBtnActionPerformed
        // TODO add your handling code here:
        if(checkDuplicate()==false){
            insertBook();
        }else{
            JOptionPane.showMessageDialog(this, "Sách này đã có trong thư viện");
        }
        
    }//GEN-LAST:event_luuBtnActionPerformed

    private void suaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBtnActionPerformed
        // TODO add your handling code here:
            updateBook();  
    }//GEN-LAST:event_suaBtnActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
       reportJasper();
    }//GEN-LAST:event_reportBtnActionPerformed

    private void sachTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sachTableMouseClicked
        // TODO add your handling code here:
        try {
            int i=sachTable.getSelectedRow();
            idEdt.setText(sachTable.getValueAt(i, 0).toString());
            nameBookEdt.setText(sachTable.getValueAt(i, 1).toString());
            authorEdt.setSelectedItem(sachTable.getValueAt(i, 2).toString());
            categoryEdt.setSelectedItem(sachTable.getValueAt(i, 3).toString());
            nxbEdt.setSelectedItem(sachTable.getValueAt(i, 4).toString());
            dateEdt.setText(sachTable.getValueAt(i, 5).toString());
            priceEdt.setText(sachTable.getValueAt(i, 6).toString());
            QuantityEdt.setText(sachTable.getValueAt(i, 7).toString());
            pageEdt.setText(sachTable.getValueAt(i, 8).toString());
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_sachTableMouseClicked

    private void nxbEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxbEdtActionPerformed

    }//GEN-LAST:event_nxbEdtActionPerformed

    private void priceEdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceEdtKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
    // Cho phép nhập số và xóa ký tự
        } else {
    JOptionPane.showMessageDialog(rootPane, "Chỉ được nhập số");
    String price = priceEdt.getText();
    priceEdt.setText(price.substring(0, price.length() - 1));
}
    }//GEN-LAST:event_priceEdtKeyReleased

    private void QuantityEdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityEdtKeyReleased
        // TODO add your handling code here:
            
              if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
    // Cho phép nhập số và xóa ký tự
        } else {
    JOptionPane.showMessageDialog(rootPane, "Chỉ dc nhập số");
            String quantity=QuantityEdt.getText().toString();
            QuantityEdt.setText(quantity.substring(0, quantity.length()-1));
              }
    }//GEN-LAST:event_QuantityEdtKeyReleased

    private void pageEdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pageEdtKeyReleased
  
     if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
    // Cho phép nhập số và xóa ký tự
        } else {
    JOptionPane.showMessageDialog(rootPane, "Chỉ dc nhập số");
            String page=pageEdt.getText().toString();
            QuantityEdt.setText(page.substring(0, page.length()-1));
              }
    }//GEN-LAST:event_pageEdtKeyReleased

    private void idEdtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idEdtFocusLost
        // TODO add your handling code here:
        if (checkDuplicate()==true) {
            JOptionPane.showMessageDialog(this,"Đã có ID này rồi");
        }
    }//GEN-LAST:event_idEdtFocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ManagementAuthor author=new ManagementAuthor();
        author.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        ManagementCategory category=new ManagementCategory();
        category.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        ManagementPublisher publisher=new ManagementPublisher();
        publisher.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void xoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBtnActionPerformed
        // TODO add your handling code here:
        deleteBook();
    }//GEN-LAST:event_xoaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QuantityEdt;
    private javax.swing.JComboBox<String> authorEdt;
    private javax.swing.JComboBox<String> categoryEdt;
    private javax.swing.JTextField dateEdt;
    private javax.swing.JTextField idEdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luuBtn;
    private javax.swing.JTextField nameBookEdt;
    private javax.swing.JComboBox<String> nxbEdt;
    private javax.swing.JTextField pageEdt;
    private javax.swing.JTextField priceEdt;
    private javax.swing.JButton reportBtn;
    private javax.swing.JTable sachTable;
    private javax.swing.JButton suaBtn;
    private javax.swing.JButton xoaBtn;
    // End of variables declaration//GEN-END:variables
}
