/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_app;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ManagementPublisher extends javax.swing.JFrame {
Connection conn;
    /**
     * Creates new form ManagementPublisher
     */
    public ManagementPublisher() {
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idEdt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nameEdt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        adressEdt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phoneEdt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        luuBtn = new javax.swing.JButton();
        suaBtn = new javax.swing.JButton();
        XoaBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nxbTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel1.setText("Quay lại");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));

        idEdt.setBackground(new java.awt.Color(102, 102, 255));
        idEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        idEdt.setForeground(new java.awt.Color(255, 255, 255));
        idEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        idEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idEdt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idEdtFocusLost(evt);
            }
        });
        jPanel1.add(idEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 245, 40));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mã NXB");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, -1));

        jLabel11.setBackground(new java.awt.Color(153, 0, 242));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, 50));

        nameEdt.setBackground(new java.awt.Color(102, 102, 255));
        nameEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        nameEdt.setForeground(new java.awt.Color(255, 255, 255));
        nameEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        nameEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(nameEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 245, 40));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tên NXB");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, -1));

        jLabel13.setBackground(new java.awt.Color(153, 0, 242));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_People_50px.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, -1));

        adressEdt.setBackground(new java.awt.Color(102, 102, 255));
        adressEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        adressEdt.setForeground(new java.awt.Color(255, 255, 255));
        adressEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        adressEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(adressEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 245, 40));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Địa chỉ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 80, -1));

        jLabel15.setBackground(new java.awt.Color(153, 0, 242));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/home_24px.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, 50));

        phoneEdt.setBackground(new java.awt.Color(102, 102, 255));
        phoneEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        phoneEdt.setForeground(new java.awt.Color(255, 255, 255));
        phoneEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        phoneEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phoneEdt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneEdtFocusLost(evt);
            }
        });
        jPanel1.add(phoneEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 245, 40));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Số điện thoại");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 107, -1));

        jLabel17.setBackground(new java.awt.Color(153, 0, 242));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/icons/icons8_Google_Mobile_50px.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 50, 40));

        luuBtn.setBackground(new java.awt.Color(255, 51, 51));
        luuBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luuBtn.setForeground(new java.awt.Color(255, 255, 255));
        luuBtn.setText("Lưu");
        luuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(luuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 100, 50));

        suaBtn.setBackground(new java.awt.Color(255, 51, 51));
        suaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        suaBtn.setForeground(new java.awt.Color(255, 255, 255));
        suaBtn.setText("Sửa");
        suaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(suaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 100, 50));

        XoaBtn.setBackground(new java.awt.Color(255, 51, 51));
        XoaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        XoaBtn.setForeground(new java.awt.Color(255, 255, 255));
        XoaBtn.setText("Xóa");
        XoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(XoaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 100, 50));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bấm vào đây nếu bạn muốn sang quản lý sách");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 275, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 670));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jLabel2.setText("Quản lý NXB");

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        nxbTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nxbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NXB", "Tên NXB", "Địa chỉ", "Số điện thoại"
            }
        ));
        nxbTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nxbTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nxbTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 780, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean checkDuplicateID(){
      String id=idEdt.getText().toString();
      boolean isExit=false;
       try {
            conn=ConnectDB.KetnoiDB();
            String sql="Select * From nxb Where MaNXB='"+id+"'";
            Statement st=conn.createStatement();
            ResultSet s=st.executeQuery(sql);
            
            if (s.next()) {
                isExit=true;
            }else{
                isExit=false;
            }
                    
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isExit;
  }
      private boolean checkDuplicatePhone(){
      String phone=phoneEdt.getText().toString();
      boolean isExit=false;
       try {
            conn=ConnectDB.KetnoiDB();
            String sql="Select * From nxb Where MaNXB='"+phone+"'";
            Statement st=conn.createStatement();
            ResultSet s=st.executeQuery(sql);
            
            if (s.next()) {
                isExit=true;
            }else{
                isExit=false;
            }
                    
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isExit;
  }
    private boolean validateNXB(){
     String phone=phoneEdt.getText().toString();
      try {
          if (!phone.matches("^(\\+84|84|0)(3|5|7|8|9)[0-9]{8}$")) {
              JOptionPane.showMessageDialog(rootPane, "Số điện thoại bắt đầu bằng +84 hoặc 0");
              return false;
          }
      } catch (Exception e) {
      e.printStackTrace();
      }
      return true;
  }
    private void deleteNXB(){
        String id=idEdt.getText().toString();
        String name=nameEdt.getText().toString();
        String adress=adressEdt.getText().toString();
        String phone=phoneEdt.getText().toString();
         try {
            conn=ConnectDB.KetnoiDB();
            String sql="Delete From nxb Where MaNXB='"+id+"'";
            Statement s=conn.createStatement();
            s.executeUpdate(sql);
            load();
            conn.close();
        } catch (Exception e) {
           e.printStackTrace();
        }
   }
    private void updateNXB(){
        String id=idEdt.getText().toString();
        String name=nameEdt.getText().toString();
        String adress=adressEdt.getText().toString();
        String phone=phoneEdt.getText().toString();
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Update nxb set TenNXB=N'"+name+"', DiaChi=N'"+adress+"' , SDT='"+phone+"' where MaNXB='"+id+"'";
            Statement s=conn.createStatement();
            s.executeUpdate(sql);
            load();
            conn.close();
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private void insertNXB(){
         String id=idEdt.getText().toString();
        String name=nameEdt.getText().toString();
        String adress=adressEdt.getText().toString();
        String phone=phoneEdt.getText().toString();
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Insert nxb Values ('"+id+"',N'"+name+"',N'"+adress+"',N'"+phone+"')";
            Statement s=conn.createStatement();
            s.executeUpdate(sql);
            load();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void load(){
        nxbTable.removeAll();
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Select * From nxb";
            Statement s=conn.createStatement();
            ResultSet rs=s.executeQuery(sql);
            
            String[] arr={"Mã NXB","Tên NXB","Địa chỉ","Số điện thoại"};
            DefaultTableModel model=new DefaultTableModel(arr,0);
            while (rs.next()) {
                Vector v=new Vector();
                v.add(rs.getString(1).toString());
                v.add(rs.getString(2).toString());
                v.add(rs.getString(3).toString());
                v.add(rs.getString(4).toString()); 
                model.addRow(v);
            }
            nxbTable.setModel(model);
            conn.close();
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private void XoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaBtnActionPerformed
        // TODO add your handling code here:
        deleteNXB();
    }//GEN-LAST:event_XoaBtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void nxbTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxbTableMouseClicked
        // TODO add your handling code here:
        try {
            int i=nxbTable.getSelectedRow();
            idEdt.setText(nxbTable.getValueAt(i, 0).toString());
            nameEdt.setText(nxbTable.getValueAt(i, 1).toString());
            adressEdt.setText(nxbTable.getValueAt(i, 2).toString());
            phoneEdt.setText(nxbTable.getValueAt(i, 3).toString());
           
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_nxbTableMouseClicked

    private void luuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBtnActionPerformed
        // TODO add your handling code here:
        if (validateNXB()==true) {
            if (checkDuplicateID()==false && checkDuplicatePhone()==false) {
                insertNXB();
            }
        }   
    }//GEN-LAST:event_luuBtnActionPerformed

    private void suaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBtnActionPerformed
        // TODO add your handling code here:
        updateNXB();
    }//GEN-LAST:event_suaBtnActionPerformed

    private void idEdtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idEdtFocusLost
        // TODO add your handling code here:
        if (checkDuplicateID()==true) {
            JOptionPane.showMessageDialog(rootPane, "Đã có ID này rồi");
        }
    }//GEN-LAST:event_idEdtFocusLost

    private void phoneEdtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneEdtFocusLost
        // TODO add your handling code here:
        if (checkDuplicatePhone()==true) {
            JOptionPane.showMessageDialog(rootPane, "Đã có SDT này rồi");
        }
    }//GEN-LAST:event_phoneEdtFocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ManagementBook book=new ManagementBook();
        book.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementPublisher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XoaBtn;
    private javax.swing.JTextField adressEdt;
    private javax.swing.JTextField idEdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luuBtn;
    private javax.swing.JTextField nameEdt;
    private javax.swing.JTable nxbTable;
    private javax.swing.JTextField phoneEdt;
    private javax.swing.JButton suaBtn;
    // End of variables declaration//GEN-END:variables
}
