/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_app;

import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author Admin
 */
public class Signup extends javax.swing.JFrame {
    Connection conn;
    /**
     * Creates new form Login
     */
    public Signup() {
        initComponents();
        setLocale(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userEdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        emailEdt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        signupBtn = new javax.swing.JToggleButton();
        loginBtn = new javax.swing.JButton();
        repassEdt = new javax.swing.JPasswordField();
        passEdt = new javax.swing.JPasswordField();
        remember = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGNUP");
        setMinimumSize(new java.awt.Dimension(1111, 659));
        setPreferredSize(new java.awt.Dimension(1111, 659));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 16, 184, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/icons/signup-library-icon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 680, 560));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Management Library");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 61, 270, 49));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Signup Page");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 20, 400, 48));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create New Account Here");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 37));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, -1));

        jLabel7.setBackground(new java.awt.Color(153, 0, 242));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 54, -1));

        userEdt.setBackground(new java.awt.Color(102, 102, 255));
        userEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        userEdt.setForeground(new java.awt.Color(255, 255, 255));
        userEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        userEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userEdt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userEdtFocusLost(evt);
            }
        });
        userEdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userEdtMouseClicked(evt);
            }
        });
        jPanel2.add(userEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 260, 40));

        jLabel8.setBackground(new java.awt.Color(153, 0, 242));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/icons/icons8_Forgot_Password_50px_4.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 54, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 80, -1));

        jLabel10.setBackground(new java.awt.Color(153, 0, 242));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 54, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Repassword");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 113, -1));

        jLabel12.setBackground(new java.awt.Color(153, 0, 242));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 54, -1));

        emailEdt.setBackground(new java.awt.Color(102, 102, 255));
        emailEdt.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        emailEdt.setForeground(new java.awt.Color(255, 255, 255));
        emailEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        emailEdt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailEdt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailEdtFocusLost(evt);
            }
        });
        emailEdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailEdtMouseClicked(evt);
            }
        });
        jPanel2.add(emailEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 260, 40));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 80, -1));

        signupBtn.setBackground(new java.awt.Color(51, 153, 255));
        signupBtn.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        signupBtn.setText("Signup");
        signupBtn.setBorder(null);
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        jPanel2.add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 270, 50));

        loginBtn.setBackground(new java.awt.Color(255, 102, 102));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 270, 50));

        repassEdt.setBackground(new java.awt.Color(102, 102, 255));
        repassEdt.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        repassEdt.setForeground(new java.awt.Color(255, 255, 255));
        repassEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        repassEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repassEdtActionPerformed(evt);
            }
        });
        jPanel2.add(repassEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 260, 40));

        passEdt.setBackground(new java.awt.Color(102, 102, 255));
        passEdt.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        passEdt.setForeground(new java.awt.Color(255, 255, 255));
        passEdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        passEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passEdtActionPerformed(evt);
            }
        });
        jPanel2.add(passEdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 260, 40));

        remember.setText("Hiện mật khẩu");
        remember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberActionPerformed(evt);
            }
        });
        jPanel2.add(remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 136, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 420, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertSignup(){
         String user=userEdt.getText().toString().trim();
        String pass=repassEdt.getText().toString().trim();
        String repass=repassEdt.getText().toString().trim();
        String email=emailEdt.getText().toString().trim();
    
        conn=ConnectDB.KetnoiDB();
        
        String sql="Insert user Values  (id,?,?,?,?)";
        try {
            
                 PreparedStatement ps=conn.prepareStatement(sql);
                 
                 ps.setString(1, user);
                 ps.setString(2, pass);
                 ps.setString(3, repass);
                 ps.setString(4, email);
                 
            ps.executeUpdate();
            

             Home h=new Home();
                h.setVisible(true);
                dispose();
            conn.close();
   
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private boolean checkDuplicateUser(){
        String user=userEdt.getText().toString();
        boolean isExit=false;
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Select * From user Where username='"+user+"'";
            Statement st=conn.createStatement();
            ResultSet s=st.executeQuery(sql);
            
            if (s.next()) {
                isExit=true;
            }else{
                isExit=false;
            }
                    
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isExit;
    }
    private boolean checkDuplicateEmail(){
        String email=emailEdt.getText().toString();
        boolean isExit=false;
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Select * From user Where email='"+email+"'";
            Statement st=conn.createStatement();
            ResultSet s=st.executeQuery(sql);
            
            if (s.next()) {
                isExit=true;
            }else{
                isExit=false;
            }
                    
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isExit;
    }
    private boolean validateSignup(){
     String user=userEdt.getText().toString().trim();
        String pass=repassEdt.getText().toString().trim();
        String repass=repassEdt.getText().toString().trim();
        String email=emailEdt.getText().toString().trim();
        if (user.equals("") || !user.matches("[a-z0-9_-]{6,12}$")) {
            JOptionPane.showMessageDialog(rootPane, "Nhập username phải có ít nhất 6 kí tự");
            return false;
        }
        if ( !pass.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,20}$")) {
            JOptionPane.showMessageDialog(rootPane, "Nhập password cần có 8 kí tự ít nhất 1 chữ cái hoa, có ít nhất 1 số và có ít nhất 1 kí tự đặc biệt ");
            return false;
        }
        if (!repass.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,20}$")||!repass.equalsIgnoreCase(pass)) {
            JOptionPane.showMessageDialog(rootPane, "Nhập repassword cần phải trùng với password");
            return false;
        }
        if (email.equals("") || !email.matches("^[A-Za-z0-9]+[A-Za-z0-9]*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)$")) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập chính xác email!");
            return false;
        }
        return true;
}

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        if (validateSignup()==true ) {
            if (checkDuplicateUser()==false && checkDuplicateEmail()==false) {
                insertSignup();
               
            }
        }
    
    }//GEN-LAST:event_signupBtnActionPerformed

    private void userEdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userEdtMouseClicked
        // TODO add your handling code here:
//       userEdt.setText("");
    }//GEN-LAST:event_userEdtMouseClicked

    private void emailEdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailEdtMouseClicked
        // TODO add your handling code here:
//        emailEdt.setText("");
    }//GEN-LAST:event_emailEdtMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        Login l=new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void userEdtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userEdtFocusLost
        // TODO add your handling code here:
        if (checkDuplicateUser()==true) {
            JOptionPane.showMessageDialog(rootPane, "username này đã có rồi xin hãy nhập username khác");
        }
    }//GEN-LAST:event_userEdtFocusLost

    private void emailEdtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailEdtFocusLost
        // TODO add your handling code here:
        if (checkDuplicateEmail()==true) {
            JOptionPane.showMessageDialog(rootPane, "Email này đã có tài khoản rồi xin hãy nhập email khác");
           String emailString= emailEdt.getText().toString();
            emailEdt.setText("");
        }
    }//GEN-LAST:event_emailEdtFocusLost

    private void repassEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repassEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repassEdtActionPerformed

    private void passEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passEdtActionPerformed

    private void rememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberActionPerformed
        // TODO add your handling code here:
        if(remember.isSelected()){
            passEdt.setEchoChar((char)0);
            repassEdt.setEchoChar((char)0);
        }else{
            passEdt.setEchoChar('*');
            repassEdt.setEchoChar('*');
        }
    }//GEN-LAST:event_rememberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailEdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passEdt;
    private javax.swing.JCheckBox remember;
    private javax.swing.JPasswordField repassEdt;
    private javax.swing.JToggleButton signupBtn;
    private javax.swing.JTextField userEdt;
    // End of variables declaration//GEN-END:variables
}
