/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_app;



import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class taovagiahanphieu extends javax.swing.JFrame {
Connection conn;
    /**
     * Creates new form taovagiahanphieu
     */
    public taovagiahanphieu() {
        initComponents();
        loaddocgiapm();
        load();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        docgia = new javax.swing.JComboBox<>();
        ngaydangki = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ngayhethan = new javax.swing.JTextField();
        taophieu = new javax.swing.JButton();
        backBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        madg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        docgia1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        themngay = new javax.swing.JTextField();
        maphieu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        giahan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tạo phiếu ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên độc giả:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 30));

        docgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docgiaActionPerformed(evt);
            }
        });
        jPanel1.add(docgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 260, 30));

        ngaydangki.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ngaydangki.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ngaydangkiFocusLost(evt);
            }
        });
        jPanel1.add(ngaydangki, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 260, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ngày đăng kí:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ngày hết hạn:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 110, 30));

        ngayhethan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayhethanActionPerformed(evt);
            }
        });
        jPanel1.add(ngayhethan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 260, 30));

        taophieu.setBackground(new java.awt.Color(255, 51, 51));
        taophieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taophieu.setForeground(new java.awt.Color(255, 255, 255));
        taophieu.setText("Tạo phiếu mượn");
        taophieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taophieuActionPerformed(evt);
            }
        });
        jPanel1.add(taophieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 290, 30));

        backBtn.setBackground(new java.awt.Color(255, 51, 51));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel1.setText("Quay lại");

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bấm vào đây để mượn sách");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 16, 160, 30));

        madg.setText("madg");
        jPanel1.add(madg, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên độc giả:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, 30));

        jPanel2.add(docgia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 260, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số ngày:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, 30));

        themngay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        themngay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                themngayKeyReleased(evt);
            }
        });
        jPanel2.add(themngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 260, 30));

        maphieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(maphieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 260, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mã phiếu:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gia hạn thêm ngày");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 290, 30));

        giahan.setBackground(new java.awt.Color(255, 51, 51));
        giahan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        giahan.setForeground(new java.awt.Color(255, 255, 255));
        giahan.setText("Gia hạn");
        giahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giahanActionPerformed(evt);
            }
        });
        jPanel2.add(giahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 237, 280, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 600, 300));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 980, 250));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1200, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean validategiahan(){
         String date=ngaydangki.getText().toString();
         String date2=ngayhethan.getText().toString();
      if (!date.matches("^\\d{4}-\\d{1,2}-\\d{1,2}$")) {
          JOptionPane.showMessageDialog(rootPane, "Hãy nhập theo định dạng ngày sinh theo Năm-Tháng-Ngày");
          return false;
      }
      if (!date2.matches("^\\d{4}-\\d{1,2}-\\d{1,2}$")) {
          JOptionPane.showMessageDialog(rootPane, "Hãy nhập theo định dạng ngày sinh theo Năm-Tháng-Ngày");
          return false;
      }
      return true;
    }
    private void giahanthem(){
        String mapm=maphieu.getText().toString();
        int them=Integer.parseInt(this.themngay.getText().toString());
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="update phieumuon set ngayhethan= DATE_ADD(ngayhethan,INTERVAL ? DAY) where mapm=?";
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setInt(1, them);
            ps.setString(2, mapm);
            ps.executeUpdate();
            load();
            conn.close();
            JOptionPane.showMessageDialog(rootPane, "Đã gia hạn thành công");
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private void load(){
         this.table.removeAll();
        try {
            conn=ConnectDB.KetnoiDB();
                String sql="SELECT phieumuon.mapm,docgia.tendg,docgia.diachi,docgia.sdt,phieumuon.ngaydangky,phieumuon.ngayhethan from phieumuon join docgia on phieumuon.madg=docgia.madg";
            Statement s=conn.createStatement();
            ResultSet rs=s.executeQuery(sql);
            
            String[] arr={"Mã phiếu","Tên độc giả","Địa chỉ","Số dt","Ngày đăng kí","Ngày hết hạn"};
            DefaultTableModel model=new DefaultTableModel(arr,0);
            while (rs.next()) {
                Vector v=new Vector();
                v.add(rs.getString(1).toString());
                v.add(rs.getString(2).toString());
                v.add(rs.getString(3).toString());
                v.add(rs.getString(4).toString()); 
                v.add(rs.getString(5).toString()); 
                v.add(rs.getString(6).toString()); 

           
                model.addRow(v);
            }
            this.table.setModel(model);
            conn.close();
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
         // lấy dữ liệu từ combobox trong tạo phiếu
    private String getIDgiahan() throws SQLException{
          String id = null;
       String name=docgia1.getSelectedItem().toString();
           conn=ConnectDB.KetnoiDB();
           String sql="select madg From docgia Where Tendg=?";
           PreparedStatement ps=conn.prepareStatement(sql);
           ps.setString(1, name);
           ResultSet rs=ps.executeQuery();
             if(rs.next()) {                 
                 id=rs.getString("madg");
             }
       
      return id;
    }
        // lấy dữ liệu từ combobox trong tạo phiếu
    private String getIDDG() throws SQLException{
          
       String name=docgia.getSelectedItem().toString();
           conn=ConnectDB.KetnoiDB();
           String sql="select madg From docgia Where Tendg=?";
           PreparedStatement ps=conn.prepareStatement(sql);
           ps.setString(1, name);
           ResultSet rs=ps.executeQuery();
             if(rs.next()) {                 
                 name=rs.getString("docgia.madg");
             }
       
      return name;
    }
    // đổ dữ liệu lên combobox trong tạo phiếu

    private void loaddocgiapm(){
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="select Tendg,madg From docgia";
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                docgia.addItem(rs.getString("tendg"));
                docgia1.addItem(rs.getString("tendg"));
               
               
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private void insertphieumuon(){
        String tendocgia=docgia.getSelectedItem().toString();
        String ngaydangki=this.ngaydangki.getText().toString();
        String ngayhethan=this.ngayhethan.getText().toString();
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="insert phieumuon values (mapm,?,?,?,?)";
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1, getIDDG());
            ps.setString(2, ngaydangki);
            ps.setString(3, ngayhethan);
            ps.setString(4, "Đang mượn");
            ps.executeUpdate();
            load();
            conn.close();
            JOptionPane.showMessageDialog(rootPane, "Tạo phiếu mượn thành công");
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private void ngayhethanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayhethanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayhethanActionPerformed

    private void taophieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taophieuActionPerformed
        // TODO add your handling code here:
        if (validategiahan()==true) {
             insertphieumuon();
        }
       
    }//GEN-LAST:event_taophieuActionPerformed

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
        int i=this.table.getSelectedRow();
        maphieu.setText(this.table.getValueAt(i, 0).toString());
        docgia1.setSelectedItem(this.table.getValueAt(i, 1));

    }//GEN-LAST:event_tableMouseClicked

    private void giahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giahanActionPerformed
        // TODO add your handling code here:
       giahanthem();
    }//GEN-LAST:event_giahanActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        muonsach m=new muonsach();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void themngayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_themngayKeyReleased
        // TODO add your handling code here:

          if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '1' || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
    // Cho phép nhập số và xóa ký tự
        } else {
    JOptionPane.showMessageDialog(rootPane, "Chi dc them 1 ngay");
            String quantityString=themngay.getText().toString();
            themngay.setText(quantityString.substring(0, quantityString.length()-1));
              }
    }//GEN-LAST:event_themngayKeyReleased

    private void ngaydangkiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ngaydangkiFocusLost
  
    }//GEN-LAST:event_ngaydangkiFocusLost

    private void docgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docgiaActionPerformed
        // TODO add your handling code here:
          String a=docgia.getSelectedItem().toString();
    try {
        madg.setText(getIDDG());
    } catch (SQLException ex) {
        Logger.getLogger(taovagiahanphieu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_docgiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taovagiahanphieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taovagiahanphieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taovagiahanphieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taovagiahanphieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taovagiahanphieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backBtn;
    private javax.swing.JComboBox<String> docgia;
    private javax.swing.JComboBox<String> docgia1;
    private javax.swing.JButton giahan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel madg;
    private javax.swing.JTextField maphieu;
    private javax.swing.JTextField ngaydangki;
    private javax.swing.JTextField ngayhethan;
    private javax.swing.JTable table;
    private javax.swing.JButton taophieu;
    private javax.swing.JTextField themngay;
    // End of variables declaration//GEN-END:variables
}
