/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_app;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class trasach extends javax.swing.JFrame {
Connection conn;
    /**
     * Creates new form trasach
     */
    public trasach() {
        initComponents();
        load();
        loadTendg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mapm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        timkiem = new javax.swing.JButton();
        trasach = new javax.swing.JButton();
        tendg = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        report = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        returnTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(255, 51, 51));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel1.setText("Quay lại");

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã phiếu mượn:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 30));
        jPanel1.add(mapm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 190, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên độc giả");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 110, 30));

        timkiem.setBackground(new java.awt.Color(255, 51, 51));
        timkiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timkiem.setForeground(new java.awt.Color(255, 255, 255));
        timkiem.setText("Tìm kiếm");
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });
        jPanel1.add(timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 290, 30));

        trasach.setBackground(new java.awt.Color(255, 51, 51));
        trasach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trasach.setForeground(new java.awt.Color(255, 255, 255));
        trasach.setText("Trả sách");
        trasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trasachActionPerformed(evt);
            }
        });
        jPanel1.add(trasach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 290, 30));

        jPanel1.add(tendg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 180, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jLabel6.setText("Sách");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 280, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 280, 10));

        reset.setBackground(new java.awt.Color(255, 51, 51));
        reset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Làm mới bảng");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 290, 30));

        report.setBackground(new java.awt.Color(255, 51, 51));
        report.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("In báo cáo");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        jPanel1.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 290, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 670));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        returnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(returnTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 720, 300));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_app/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        jLabel5.setText("Trả Sách");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 280, 90));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 280, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 800, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void report2(){
    try {        
            conn=ConnectDB.KetnoiDB();
           String path="C:\\Users\\Admin\\JaspersoftWorkspace\\MyReports\\trasach2.jrxml";
           JasperReport jr= JasperCompileManager.compileReport(path);
           JasperPrint jp=JasperFillManager.fillReport(jr, null,conn);
           JasperViewer.viewReport(jp,false);
          conn.close();
           } catch (Exception e) {
       e.printStackTrace();
       }
    }
    private void report(String a){
        try {
           conn=ConnectDB.KetnoiDB();
           String path="C:\\Users\\Admin\\JaspersoftWorkspace\\MyReports\\trasach.jrxml";
           JasperReport jr= JasperCompileManager.compileReport(path);
           HashMap<String,Object> pa=new HashMap<>();
           pa.put("mapm_search", a);
           pa.put("tendg_search",getIDDG());
           JasperPrint jp=JasperFillManager.fillReport(jr, pa,conn);
           JasperViewer.viewReport(jp,false);
          conn.close();
       } catch (Exception e) {
       e.printStackTrace();
       }
    }
    private boolean checktrangthai(){
        String id=this.mapm.getText().toString();
        boolean isExit=false;
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="select trangthai from phieumuon where trangthai=? and mapm=?";
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1, "Đã trả");
            ps.setString(2, id);
            ResultSet rs=ps.executeQuery();
            if (rs.next()) {
                isExit=true;
            }else{
                isExit=false;
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
        return isExit;
    }
    private void setslpm(){
        String id=this.mapm.getText().toString();
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Update chitietmuon set soluong=0 where mapm=?";
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1, id);
            ps.executeUpdate();
            conn.close();
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private void  updatecountbookPlus(){
        String mapm=this.mapm.getText().toString();
        int i=returnTable.getSelectedRow();
        int sl=Integer.parseInt(returnTable.getValueAt(i, 7).toString());
      try {
      conn=ConnectDB.KetnoiDB();
      String sql="Update sach join chitietmuon on sach.MaSach=chitietmuon.masach set sach.SoLuong= sach.SoLuong+? where chitietmuon.mapm=?;";
      PreparedStatement ps=conn.prepareStatement(sql);
      ps.setInt(1, sl);
      ps.setString(2,mapm );
      ps.executeUpdate();
      load();
          JOptionPane.showMessageDialog(rootPane, "Đã sửa lại số lượng sách");
          conn.close();
      } catch (Exception e) {
    e.printStackTrace();
      }
   }
    private void trasach(){
          String mapm=this.mapm.getText().toString();
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="Update phieumuon set trangthai=? where phieumuon.mapm=? and phieumuon.madg=?";
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1, "Đã trả");
            ps.setString(2,mapm );
            ps.setString(3,getIDDG() );
            ps.executeUpdate();
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private void timkiem(){
        String mapm=this.mapm.getText().toString();
         this.returnTable.removeAll();
        try {
            conn=ConnectDB.KetnoiDB();
                String sql="select phieumuon.mapm,docgia.tendg,docgia.diachi,docgia.sdt,phieumuon.ngaydangky,phieumuon.ngayhethan,phieumuon.trangthai from phieumuon join docgia on phieumuon.madg=docgia.madg where phieumuon.mapm=? or phieumuon.madg=? ";
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1, mapm);
            ps.setString(2, getIDDG());
            ResultSet rs=ps.executeQuery();
            
            String[] arr={"Mã phiếu","Tên độc giả","Địa chỉ","Số dt","Ngày đăng kí","Ngày hết hạn","Trạng thái"};
            DefaultTableModel model=new DefaultTableModel(arr,0);
            while (rs.next()) {
                Vector v=new Vector();
                v.add(rs.getString(1).toString());
                v.add(rs.getString(2).toString());
                v.add(rs.getString(3).toString());
                v.add(rs.getString(4).toString()); 
                v.add(rs.getString(5).toString()); 
                v.add(rs.getString(6).toString()); 
                v.add(rs.getString(7).toString()); 

           
                model.addRow(v);
            }
            this.returnTable.setModel(model);
            conn.close();
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private String getIDDG() throws SQLException{
         String id = null;
       String name=tendg.getSelectedItem().toString();
           conn=ConnectDB.KetnoiDB();
           String sql="select phieumuon.madg From phieumuon join docgia on phieumuon.madg=docgia.madg Where Tendg=?";
           PreparedStatement ps=conn.prepareStatement(sql);
           ps.setString(1, name);
           ResultSet rs=ps.executeQuery();
             if(rs.next()) {                 
                 id=rs.getString("phieumuon.madg");
             }
       
      return id;
    }
    private void loadTendg(){
        try {
            conn=ConnectDB.KetnoiDB();
            String sql="select docgia.tendg from phieumuon JOIN docgia on phieumuon.madg=docgia.madg";
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                tendg.addItem(rs.getString("tendg"));
           
               
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    
    private void load(){
          this.returnTable.removeAll();
        try {
            conn=ConnectDB.KetnoiDB();
                String sql="select phieumuon.mapm,docgia.tendg,docgia.diachi,docgia.sdt,phieumuon.ngaydangky,phieumuon.ngayhethan,phieumuon.trangthai ,sum(soluong) from phieumuon join docgia on phieumuon.madg=docgia.madg join chitietmuon on phieumuon.mapm=chitietmuon.mapm GROUP by mapm;;";
            Statement s=conn.createStatement();
            ResultSet rs=s.executeQuery(sql);
            
            String[] arr={"Mã phiếu","Tên độc giả","Địa chỉ","Số dt","Ngày đăng kí","Ngày hết hạn","Trạng thái","Tổng sách mượn"};
            DefaultTableModel model=new DefaultTableModel(arr,0);
            while (rs.next()) {
                Vector v=new Vector();
                v.add(rs.getString(1).toString());
                v.add(rs.getString(2).toString());
                v.add(rs.getString(3).toString());
                v.add(rs.getString(4).toString()); 
                v.add(rs.getString(5).toString()); 
                v.add(rs.getString(6).toString()); 
                v.add(rs.getString(7).toString()); 
                v.add(rs.getString(8).toString()); 

           
                model.addRow(v);
            }
            this.returnTable.setModel(model);
            conn.close();
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_timkiemActionPerformed

    private void trasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trasachActionPerformed
        // TODO add your handling code here:
        if (checktrangthai()==false) {
         trasach();
        updatecountbookPlus();
        setslpm();
        load();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Bạn độc giả có phiếu mượn này đã trả sách rồi");
        }
        
    }//GEN-LAST:event_trasachActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_resetActionPerformed

    private void returnTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnTableMouseClicked
        // TODO add your handling code here:
        int i=this.returnTable.getSelectedRow();
        this.mapm.setText(this.returnTable.getValueAt(i, 0).toString());
        this.tendg.setSelectedItem(this.returnTable.getValueAt(i, 1));
    }//GEN-LAST:event_returnTableMouseClicked

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        if(!mapm.getText().toString().isEmpty() && tendg.getSelectedItem()!=null){
           String a=mapm.getText().toString();
        String b=tendg.getSelectedItem().toString();
        report(a);
        }else{
        report2();
        }
    }//GEN-LAST:event_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trasach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trasach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trasach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trasach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trasach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mapm;
    private javax.swing.JButton report;
    private javax.swing.JButton reset;
    private javax.swing.JTable returnTable;
    private javax.swing.JComboBox<String> tendg;
    private javax.swing.JButton timkiem;
    private javax.swing.JButton trasach;
    // End of variables declaration//GEN-END:variables
}
